// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PF-3.1 Campos incompletos', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PF-3.1 Campos incompletos', async function() {
    await driver.get("https://finalprojectjuansehenao.herokuapp.com/")
    await driver.manage().window().setRect({ width: 1089, height: 605 })
    await driver.findElement(By.css("a:nth-child(4) > button")).click()
    await driver.findElement(By.css("button:nth-child(2)")).click()
  })
})
